### ISSUE TITLE
Error running code. How to change the connected device?

### ISSUE THREAD

**Issue by SergeyMi37** [AlexeyBond/Irene-Voice-Assistant#3]
```
 python -m irene
 ...
   raise PortAudioError(errormsg, err, hosterror_info)
sounddevice.PortAudioError: Error opening RawInputStream: Unanticipated host error [PaErrorCode -9999]: 'Системной функции передан неправильный параметр.' [MME error 11]
```
In the original it was like this
```
python runva_vosk.py -d 24
```

**Comment by SergeyMi37** [comment]
Tested for Windows

**Comment by AlexeyBond** [comment]
If chosen device is the issue, try changing settings of `local_input_sounddevice_vosk` plugin, specifically `deviceId` field.

**Comment by SergeyMi37** [comment]
Where do the settings change?
And how can I see their list?
Answer:
In the data folder (by default it is created with the name irene in the user's home folder) - a config subfolder, in it local_input_sounddevice_vosk.yaml with the settings of this plugin.

**Comment by SergeyMi37** [comment]
Thx
